spring:
  application:
    name: Resilence_4j_Demo
server:
  port: 1111
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    circuitbreakerevents:
      enabled: true
resilience4j:
 circuitbreaker:
  configs:
   default:
    registerHealthIndicator: true
    slidingWindowType: COUNT_BASED
    slidingWindowSize: 10
    minimumNumberOfCalls: 5
    waitDurationInOpenState: 5s
    failureRateThreshold: 50
    permittedNumberOfCallsInHalfOpenState: 3
  instances:
   myService:
     baseConfig: default
     waitDurationInOpenState: 5000
